package com.limh.spikesystem.activity.dao;

import com.limh.spikesystem.activity.dto.ActivityInfoDTO;

public interface ActivityInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insert(ActivityInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insertSelective(ActivityInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    ActivityInfoDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityInfoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityInfoDTO record);
}