package com.limh.spikesystem.mapper;


import com.limh.spikesystem.entity.ActivityInfoPO;

public interface ActivityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insert(ActivityInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int insertSelective(ActivityInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    ActivityInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityInfoPO record);
}