package com.limh.spikesystem.mapper;


import com.limh.spikesystem.entity.StockPO;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insert(StockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int insertSelective(StockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    StockPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockPO record);
}