package com.limh.spikesystem.product.dao;
import com.limh.spikesystem.product.dto.ProductDTO;
public interface ProductDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insert(ProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int insertSelective(ProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    ProductDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductDTO record);
}